.TH kbox-login 1 LOCAL

.SH NAME

kbox-login -- prompt for credentials and start a shell 

.SH DESCRIPTION

This is a simple login helper for remote access to KBOX on Android.
It prompts for user and password and, if they match the values set
in /etc/kbox-passwd, starts a shell

.SH CAVEATS

kbox-login is not at all secure, and is not indended to be used in
any kind of security-critical setup.


.SH AUTHOR

kbox-login is maintained by Kevin Boone and is part of the KBOX system 
for Android


